java_test(
  name = 'AllTests',
  srcs = glob(['*.java']),
  deps = [
    '//java/org/infalible/selenium/remote',
    '//java/org/infalible/selenium/remote/json',
    '//java/org/infalible/testing/junit',
    '//third-party/java/gson',
    '//third-party/java/guava',
    '//third-party/java/junit',
    '//third-party/java/selenium',
  ],
)