java_library(
    name = "remote",
    srcs = glob(["*.java"]),
    deps = [
        "//java/org/infalible/selenium/remote/json",
        "//third-party/java/gson",
        "//third-party/java/guava",
        "//third-party/java/selenium",
    ],
    visibility = [
        "//javatests/org/infalible/selenium/remote:__pkg__",
    ]
)
