java_library(
    name = "json",
    srcs = glob(["*.java"]),
    deps = [
        "//third-party/java/gson",  
    ],
    visibility = [
        "//java/org/infalible/selenium/remote:__subpackages__",
        "//javatests/org/infalible/selenium/remote:__subpackages__",
    ]
)