java_library(
    name = "json",
    srcs = glob(["*.java"]),
    deps = [
        "//third-party/java/gson",
        "//third-party/java/selenium",
    ],
    visibility = [
        "//java/org/infalible/selenium/remote/session:__subpackages__",
        "//javatests/org/infalible/selenium/remote/session:__subpackages__",
    ]
)