java_test(
  name = 'AllTests',
  srcs = glob(['*.java']),
  deps = [
    '//java/org/infalible/selenium/w3c',
    '//java/org/infalible/testing/junit',
    '//third-party/java/guava',
    '//third-party/java/junit',
  ],
)